Fix: CVE-2017-18925
Signed-off-by: Sandio Araico Sanchez <sandino@sandino.net>
Bug #540006
hardened mode for opentmpfiles
Ignore some recursive options
Refuse to remove root-owned dirs and files
Refuse to chmod/chdir/chown user-owned dirs and files
Check non-existence before creating a directory
Ensure directory has been newly created before chown/chmod/chgrp
exit on error

diff --git a/tmpfiles b/tmpfiles
--- a/tmpfiles
+++ b/tmpfiles
@@ -29,6 +29,20 @@ checkprefix() {
 	return 1
 }
 
+owned_by_root() {
+	local path="$1"
+	if [ -z "$path" ] ; then
+		echo "Missing parameter" >&2
+		return 404
+	fi
+	FOUND=$(find "$path" -maxdepth 0 -uid 0 -gid 0)
+	if [ -z $FOUND ] ; then
+		echo "Not owned by root" >&2
+		return 403
+	fi
+	return 0
+}
+
 warninvalid() {
 	printf "tmpfiles: ignoring invalid entry on line %d of \`%s'\n" "$LINENUM" "$FILE"
 	error=$(( error+1 ))
@@ -45,6 +59,7 @@ dryrun_or_real() {
 		dryrun=echo
 	fi
 	$dryrun "$@"
+	return $?
 }
 
 _chattr() {
@@ -55,6 +70,10 @@ _chattr() {
 		*) attr="+$attr" ;;
 	esac
 	local IFS=
+	if ! owned_by_root $1 ; then
+		echo "cowardly refusing to chattr" >&2
+		return 107
+	fi
 	dryrun_or_real chattr $1 "$attr" -- $3
 }
 
@@ -66,33 +85,26 @@ relabel() {
 	status=0
 	for path in ${paths}; do
 		if [ -e "$path" ]; then
+			if ! owned_by_root $1 ; then
+				echo "cowardly refusing to relabel" >&2
+				return 108
+			fi
 			if [ -x /sbin/restorecon ]; then
-				dryrun_or_real restorecon $CHOPTS "$path"
+				dryrun_or_real restorecon "$path"
 				x=$?
 				if [ $x -ne 0 ]; then
-					status=$x
+					echo "error on restorecon"  >&2
+					exit $x
 				fi
 			fi
 			if [ $uid != '-' ]; then
-				dryrun_or_real chown $CHOPTS "$uid" "$path"
-				x=$?
-				if [ $x -ne 0 ]; then
-					status=$x
-				fi
+				dryrun_or_real _chown "$uid" "$path"
 			fi
 			if [ $gid != '-' ]; then
-				dryrun_or_real chgrp $CHOPTS "$gid" "$path"
-				x=$?
-				if [ $x -ne 0 ]; then
-					status=$x
-				fi
+				dryrun_or_real _chgrp "$gid" "$path"
 			fi
 			if [ $mode != '-' ]; then
-				dryrun_or_real chmod $CHOPTS "$mode" "$path"
-				x=$?
-				if [ $x -ne 0 ]; then
-					status=$x
-				fi
+				dryrun_or_real _chmod "$mode" "$path"
 			fi
 		fi
 	done
@@ -109,14 +121,86 @@ splitpath() {
 
 _restorecon() {
     local path=$1
+	if ! owned_by_root $1 ; then
+		echo "cowardly refusing to restorecon" >&2
+		return 103
+	fi
     if [ -x /sbin/restorecon ]; then
         dryrun_or_real restorecon -F $(splitpath "$path")
     fi
 }
 
+_chmod() {
+    local path=$2 mode=$1
+	if ! owned_by_root "$path" ; then
+		echo "cowardly refusing to chmod" >&2
+		return 106
+	fi
+	dryrun_or_real chmod $mode "$path"
+	x=$?
+	if [ $x -ne 0 ]; then
+		echo "error on chmod"  >&2
+		exit $x
+	fi
+}
+
+_chown() {
+    local path=$2 uid=$1
+	if ! owned_by_root "$path" ; then
+		echo "cowardly refusing to chmod" >&2
+		return 107
+	fi
+	dryrun_or_real chown $uid "$path"
+	x=$?
+	if [ $x -ne 0 ]; then
+		echo "error on chown"  >&2
+		exit $x
+	fi
+}
+
+_chgrp() {
+    local path=$2 gid=$1
+	if ! owned_by_root "$path" ; then
+		echo "cowardly refusing to chgrp" >&2
+		return 108
+	fi
+	dryrun_or_real chgrp $gid "$path"
+	x=$?
+	if [ $x -ne 0 ]; then
+		echo "error on chgrp"  >&2
+		exit $x
+	fi
+}
+
+_rm_f() {
+    	local path=$1 
+	if [ ! -e "$path" ] ; then
+		echo "file does not exist" >&2
+		return 112
+	fi
+	if owned_by_root "$path" ; then
+		echo "cowardly refusing to rm" >&2
+		return 113
+	fi
+	rm -f "$path"
+}
+
 createdirectory() {
 	local mode="$1" uid="$2" gid="$3" path="$4"
-	dryrun_or_real mkdir -p "$path"
+	# Do nothing if existing directory
+	# avoids race condition
+	if [ -e "$path" ] ; then
+		echo "Directory already exists" >&2
+		return 101
+	fi
+	dryrun_or_real mkdir "$path"
+	# only continue on successful created directory 
+	# avoids rrace condition
+	x=$?
+	if [ $x -ne 0 ] ; then
+		echo "Could not create directory" >&2
+		exit $x
+	fi
 	if [ "$uid" = - ]; then
 		uid=root
 	fi
@@ -126,14 +210,18 @@ createdirectory() {
 	if [ "$mode" = - ]; then
 		mode=0755
 	fi
-	dryrun_or_real chown $uid "$path"
-	dryrun_or_real chgrp $gid "$path"
-	dryrun_or_real chmod $mode "$path"
+	dryrun_or_real _chown $uid "$path"
+	dryrun_or_real _chgrp $gid "$path"
+	dryrun_or_real _chmod $mode "$path"
 }
 
 createfile() {
 	local mode="$1" uid="$2" gid="$3" path="$4"
 	dryrun_or_real touch "$path"
+	if ! owned_by_root "$path" ; then
+		echo "cowardly refusing to chown/chgrp/chmod" >&2
+		return 106
+	fi
 	if [ "$uid" = - ]; then
 		uid=root
 	fi
@@ -143,14 +231,27 @@ createfile() {
 	if [ "$mode" = - ]; then
 		mode=0644
 	fi
-	dryrun_or_real chown $uid "$path"
-	dryrun_or_real chgrp $gid "$path"
-	dryrun_or_real chmod $mode "$path"
+	dryrun_or_real _chown $uid "$path"
+	dryrun_or_real _chgrp $gid "$path"
+	dryrun_or_real _chmod $mode "$path"
 }
 
 createpipe() {
 	local mode="$1" uid="$2" gid="$3" path="$4"
+	# Do nothing if existing pipe
+	# avoids race condition
+	if [ -e "$path" ] ; then
+		echo "Pipe already exists" >&2
+		return 104
+	fi
 	dryrun_or_real mkfifo "$path"
+	# only continue on successful created pipe 
+	# avoids rrace condition
+	x=$?
+	if [ $x -ne 0 ] ; then
+		echo "Could not create pipe" >&2
+		exit $x
+	fi
 	if [ "$uid" = - ]; then
 		uid=root
 	fi
@@ -160,9 +261,9 @@ createpipe() {
 	if [ "$mode" = - ]; then
 		mode=0644
 	fi
-	dryrun_or_real chown $uid "$path"
-	dryrun_or_real chgrp $gid "$path"
-	dryrun_or_real chmod $mode "$path"
+	dryrun_or_real _chown $uid "$path"
+	dryrun_or_real _chgrp $gid "$path"
+	dryrun_or_real _chmod $mode "$path"
 }
 
 _b() {
@@ -179,9 +280,14 @@ _b() {
 	fi
 	if [ ! -e "$path" ]; then
 		dryrun_or_real mknod -m $mode $path b ${arg%:*} ${arg#*:}
+		x=$?
+		if [ $x -ne 0 ]; then
+			echo "error on mknod"  >&2
+			exit $x
+		fi
 		_restorecon "$path"
-		dryrun_or_real chown $uid "$path"
-		dryrun_or_real chgrp $gid "$path"
+		dryrun_or_real _chown $uid "$path"
+		dryrun_or_real _chgrp $gid "$path"
 	fi
 }
 
@@ -199,28 +305,20 @@ _c() {
 	fi
 	if [ ! -e "$path" ]; then
 		dryrun_or_real mknod -m $mode $path c ${arg%:*} ${arg#*:}
+		x=$?
+		if [ $x -ne 0 ]; then
+			echo "error on mknod"  >&2
+			exit $x
+		fi
 		_restorecon "$path"
-		dryrun_or_real chown $uid "$path"
-		dryrun_or_real chgrp $gid "$path"
+		dryrun_or_real _chown $uid "$path"
+		dryrun_or_real _chgrp $gid "$path"
 	fi
 }
 
 _C() {
 	# recursively copy a file or directory
-	local path=$1 mode=$2 uid=$3 gid=$4 age=$5 arg=$6
-	if [ ! -e "$path" ]; then
-		dryrun_or_real cp -r "$arg" "$path"
-		_restorecon "$path"
-		if [ $uid != '-' ]; then
-			dryrun_or_real chown "$uid" "$path"
-		fi
-		if [ $gid != '-' ]; then
-			dryrun_or_real chgrp "$gid" "$path"
-		fi
-		if [ $mode != '-']; then
-			dryrun_or_real chmod "$mode" "$path"
-		fi
-	fi
+	return 501
 }
 
 _f() {
@@ -244,6 +342,11 @@ _F() {
 	[ $CREATE -gt 0 ] || return 0
 
 	dryrun_or_real rm -f "$path"
+	x=$?
+	if [ $x -ne 0 ]; then
+		echo "error on rm"  >&2
+		exit $x
+	fi
 	createfile "$mode" "$uid" "$gid" "$path"
 	if [ -n "$arg" ]; then
 		_w "$@"
@@ -266,12 +369,12 @@ _D() {
 	# Create or empty a directory
 	local path=$1 mode=$2 uid=$3 gid=$4
 
-	if [ -d "$path" ] && [ $REMOVE -gt 0 ]; then
-		dryrun_or_real find "$path" -mindepth 1 -maxdepth 1 -xdev -exec rm -rf {} +
-		_restorecon "$path"
-	fi
-
-	if [ $CREATE -gt 0 ]; then
+	if [ -d "$path" ] ; then
+		if owned_by_root "$path" ; then
+			echo "Cowardly refusing to remove directory" >&2
+			return 102
+		fi
+		dryrun_or_real rm -rf "$path"
 		createdirectory "$mode" "$uid" "$gid" "$path"
 		_restorecon "$path"
 	fi
@@ -320,6 +423,11 @@ _L() {
 	local path=$1 mode=$2 uid=$3 gid=$4 age=$5 arg=$6
 	if [ ! -e "$path" ]; then
 		dryrun_or_real ln -s "$arg" "$path"
+		x=$?
+		if [ $x -ne 0 ]; then
+			echo "error on ln"  >&2
+			exit $x
+		fi
 	fi
 	_restorecon "$path"
 }
@@ -367,9 +475,23 @@ _r() {
 	status=0
 	for path in ${paths}; do
 		if [ -f "$path" ]; then
-			dryrun_or_real rm -f "$path"
+			if ! owned_by_root "$path" ; then
+				dryrun_or_real rm -f "$path"
+				x=$?
+				if [ $x -ne 0 ]; then
+					echo "error on rm"  >&2
+					exit $x
+				fi
+			fi
 		elif [ -d "$path" ]; then
-			dryrun_or_real rmdir "$path"
+			if ! owned_by_root "$path" ; then
+				dryrun_or_real rmdir "$path"
+				x=$?
+				if [ $x -ne 0 ]; then
+					echo "error on rmdir"  >&2
+					exit $x
+				fi
+			fi
 		fi
 		x=$?
 		if [ $x -ne 0 ]; then
@@ -391,10 +513,14 @@ _R() {
 	status=0
 	for path in ${paths}; do
 		if [ -d "$path" ]; then
+			if owned_by_root "$path" ; then
+				echo "cowardly refusing to remove directory" >&2
+				return 109
+			fi
 			dryrun_or_real rm -rf --one-file-system "$path"
 			x=$?
 			if [ $x -ne 0 ]; then
-				status=$x
+				exit $x
 			fi
 	fi
 	done
@@ -405,6 +531,10 @@ _w() {
 	# Write the argument parameter to a file, if it exists.
 	local path=$1 mode=$2 uid=$3 gid=$4 age=$5 arg=$6
 	if [ -f "$path" ]; then
+		if owned_by_root "$path" ; then
+			echo "cowardly refusing to write file" >&2
+			return 110
+		fi
 		if [ $DRYRUN -eq 1 ]; then
 			echo "echo \"$arg\" >>\"$path\""
 		else
@@ -414,21 +544,8 @@ _w() {
 }
 
 _z() {
-	# Set ownership, access mode and relabel security context of a file or
-	# directory if it exists. Lines of this type accept shell-style globs in
-	# place of normal path names.
-	[ $CREATE -gt 0 ] || return 0
-
-	relabel "$@"
-}
-
-_Z() {
-	# Recursively set ownership, access mode and relabel security context of a
-	# path and all its subdirectories (if it is a directory). Lines of this type
-	# accept shell-style globs in place of normal path names.
-	[ $CREATE -gt 0 ] || return 0
-
-	CHOPTS=-R relabel "$@"
+	echo "Ignoring recursively *"
+	return 111
 }
 
 BOOT=0 CREATE=0 REMOVE=0 CLEAN=0 VERBOSE=0 DRYRUN=0 error=0 LINENO=0
@@ -565,7 +682,7 @@ for FILE in $tmpfiles_d ; do
 
 		if [ $FORCE -gt 0 ]; then
 			case $cmd in
-				p|L|c|b) [ -f "$path" ] && dryrun_or_real rm -f "$path"
+				p|L|c|b) [ -f "$path" ] && dryrun_or_real _rm_f "$path"
 			esac
 		fi
 
